# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8eec2d6ffa687ae4f16212798f83b50b97202436549809debed1ab701286691b485814bf70f4d26ff8f3ad0497fe4475d82ddaf6af0a3cdf0cfcf099d1105a19

test:
  secret_key_base: 908d190c22fedeca26a0923795070e227def7c37476fbd579b87288069e4337e413feb6f94f5ea19428f836945b206e67bc9a4f153b1f57af4d4ca03166f9083

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
